import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    "nav.browse": "Browse",
    "nav.messages": "Messages",
    "nav.account": "Account",
    "nav.myProfile": "My Profile",
    "nav.logOut": "Log Out",
    "nav.signIn": "Sign In",
    "nav.getStarted": "Get Started",
    
    // Hero
    "hero.badge": "Find Your Perfect Co-Founder",
    "hero.title1": "Find Your Perfect",
    "hero.title2": "Teammate",
    "hero.description": "Whether you're building a startup or competing in hackathons, connect with the right people to bring your ideas to life.",
    "hero.getStarted": "Get Started",
    "hero.browseNow": "Browse Now",
    "hero.freeJoin": "✨ Free to join • 🔒 No credit card required",
    "hero.activeMembers": "Active Members",
    "hero.teamsFormed": "Teams Formed",
    "hero.universities": "Universities",
    "hero.testimonial": "Found her CTO in 2 days",
    
    // PathSelector
    "path.title": "Choose Your Path",
    "path.description": "Whether you're competing or building the next big thing, find your perfect teammates",
    "path.competitions": "Competitions & Hackathons",
    "path.competitionsDesc": "Find teammates for hackathons, case competitions, innovation challenges, and academic contests",
    "path.competitionsFeature1": "Perfect for students and competition enthusiasts",
    "path.competitionsFeature2": "Short-term projects with clear deadlines",
    "path.competitionsFeature3": "Match by skills, timezone, and availability",
    "path.findCompetitionTeams": "Find Competition Teams",
    "path.startups": "Startups & Ventures",
    "path.startupsDesc": "Connect with co-founders and early team members to build your startup from idea to launch",
    "path.startupsFeature1": "For aspiring founders and entrepreneurs",
    "path.startupsFeature2": "Long-term commitment and equity partnerships",
    "path.startupsFeature3": "Find co-founders aligned with your vision",
    "path.findCoFounders": "Find Co-founders",
    
    // Features
    "features.title1": "Everything You Need to",
    "features.title2": "Find Your Team",
    "features.description": "CoLabNow makes team building simple, fast, and effective for aspiring entrepreneurs and students.",
    "features.smartMatching": "Smart Matching",
    "features.smartMatchingDesc": "Find co-founders based on skills, interests, timezone, and goals. Our filters help you discover the perfect match.",
    "features.teamBuilding": "Team Building",
    "features.teamBuildingDesc": "Browse teams looking for members or create your own team listing. Perfect for hackathons and startup competitions.",
    "features.advancedFilters": "Advanced Filters",
    "features.advancedFiltersDesc": "Filter by role, industry, school, language, location, and more. Find exactly who you're looking for.",
    "features.directConnect": "Direct Connect",
    "features.directConnectDesc": "Message potential co-founders directly. Build relationships before committing to collaboration.",
    "features.globalCommunity": "Global Community",
    "features.globalCommunityDesc": "Connect with entrepreneurs and innovators from universities and communities worldwide.",
    "features.fastSimple": "Fast & Simple",
    "features.fastSimpleDesc": "Create your profile in minutes and start connecting. No complicated onboarding or lengthy forms.",
    
    // HowItWorks
    "how.title": "How It Works",
    "how.description": "Get started in minutes and find your perfect co-founder or team",
    "how.step1": "Create Your Profile",
    "how.step1Desc": "Sign up and tell us about your skills, interests, and what you're looking for in a co-founder or team.",
    "how.step2": "Browse & Filter",
    "how.step2Desc": "Search through profiles of entrepreneurs and teams. Use filters to find the perfect match for your needs.",
    "how.step3": "Connect & Chat",
    "how.step3Desc": "Reach out to potential co-founders or teams. Have conversations to see if you're aligned.",
    "how.step4": "Build Together",
    "how.step4Desc": "Start your journey! Work on your startup, compete in hackathons, or bring your ideas to life.",
    
    // CTA
    "cta.title": "Ready to Find Your Co-Founder?",
    "cta.description": "Join thousands of entrepreneurs, developers, and innovators who are building the future together.",
    "cta.getStartedFree": "Get Started Free",
    "cta.browseProfiles": "Browse Profiles",
    
    // Footer
    "footer.tagline": "Connecting entrepreneurs and innovators to build the future together.",
    "footer.platform": "Platform",
    "footer.browse": "Browse",
    "footer.howItWorks": "How It Works",
    "footer.successStories": "Success Stories",
    "footer.resources": "Resources",
    "footer.blog": "Blog",
    "footer.faq": "FAQ",
    "footer.support": "Support",
    "footer.company": "Company",
    "footer.about": "About",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.copyright": "© 2025 CoLabNow. All rights reserved.",
    
    // Auth
    "auth.welcome": "Welcome to CoLabNow",
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.fullName": "Full Name",
    "auth.signInButton": "Sign In",
    "auth.signUpButton": "Sign Up",
    "auth.noAccount": "Don't have an account?",
    "auth.haveAccount": "Already have an account?",
    "auth.signUpLink": "Sign Up",
    "auth.signInLink": "Sign In",
    "auth.signUpDesc": "Join CoLabNow and start building your dream team",
    "auth.signInDesc": "Sign in to continue your journey",
    "auth.passwordHint": "At least 6 characters",
    "auth.loading": "Loading...",
    "auth.terms": "By continuing, you agree to our Terms of Service and Privacy Policy",
    
    // Profile
    "profile.myProfile": "My Profile",
    "profile.fullName": "Full Name",
    "profile.school": "School/University",
    "profile.role": "Role",
    "profile.bio": "Bio",
    "profile.location": "Location",
    "profile.timezone": "Timezone",
    "profile.languages": "Languages",
    "profile.skills": "Skills",
    "profile.linkedin": "LinkedIn URL",
    "profile.github": "GitHub URL",
    "profile.portfolio": "Portfolio URL",
    "profile.availability": "Availability",
    "profile.available": "Available",
    "profile.busy": "Busy",
    "profile.notLooking": "Not Looking",
    "profile.saveChanges": "Save Changes",
    "profile.experienceLevel": "Experience Level",
    "profile.beginner": "Beginner",
    "profile.intermediate": "Intermediate",
    "profile.advanced": "Advanced",
    "profile.expert": "Expert",
    "profile.loading": "Loading...",
    "profile.interestedIn": "I'm interested in",
    "profile.competitions": "Competitions & Hackathons",
    "profile.startups": "Startups & Ventures",
    "profile.both": "Both",
    "profile.bioPlaceholder": "Tell us about yourself...",
    "profile.addSkill": "Add a skill...",
    "profile.add": "Add",
    "profile.saving": "Saving...",
    "profile.update": "Update Profile",
    "profile.updating": "Updating...",
    "profile.success": "Success",
    "profile.profileUpdated": "Profile updated successfully!",
    
    // Browse
    "browse.title": "Browse",
    "browse.profiles": "Profiles",
    "browse.teams": "Teams",
    "browse.searchPlaceholder": "Search by name, skills, or role...",
    "browse.filterByRole": "Filter by Role",
    "browse.all": "All",
    "browse.connect": "Connect",
    "browse.viewTeam": "View Team",
    "browse.openRoles": "Open Roles",
    "browse.teamSize": "Team Size",
    "browse.members": "members",
    "browse.loading": "Loading...",
    "browse.loadingDesc": "Finding your perfect match",
    "browse.discover": "Discover Your",
    "browse.perfectMatch": "Perfect Match",
    "browse.browseDesc": "Browse profiles of aspiring entrepreneurs and teams looking for members",
    "browse.filters": "Filters",
    "browse.role": "Role",
    "browse.developer": "Developer",
    "browse.designer": "Designer",
    "browse.business": "Business",
    "browse.marketing": "Marketing",
    "browse.industry": "Industry",
    "browse.availability": "Availability",
    "browse.fulltime": "Full-time",
    "browse.parttime": "Part-time",
    "browse.flexible": "Flexible",
    "browse.noProfiles": "No profiles found. Be the first to create one!",
    "browse.noTeams": "No teams found. Create your team and start recruiting!",
    
    // Messages
    "message.sendTo": "Send Message to",
    "message.dialogDesc": "Send a direct message to connect and discuss potential collaboration opportunities.",
    "message.subject": "Subject",
    "message.subjectPlaceholder": "What would you like to discuss?",
    "message.message": "Message",
    "message.messagePlaceholder": "Write your message here...",
    "message.cancel": "Cancel",
    "message.send": "Send Message",
    "message.sending": "Sending...",
    "message.sent": "Message Sent",
    "message.sentDesc": "Your message has been sent successfully!",
    "message.sendError": "Failed to send message",
    "message.emptyMessage": "Empty message",
    "message.emptyMessageDesc": "Please write a message before sending.",
    "message.loginRequired": "Login required",
    "message.loginRequiredDesc": "You need to be logged in to send messages.",
    "message.noSubject": "No subject",

    // Messages Page
    "messages.inbox": "Inbox",
    "messages.inboxDesc": "View and manage your messages",
    "messages.loading": "Loading messages...",
    "messages.noMessages": "No messages yet",
    "messages.new": "New",
    "messages.back": "Back",
    "messages.reply": "Reply",
    "messages.replyPlaceholder": "Type your reply here...",
    "messages.sendReply": "Send Reply",
    "messages.replySent": "Reply Sent",
    "messages.replySentDesc": "Your reply has been sent successfully!",
    "messages.selectMessage": "Select a message to view",
    "messages.loadError": "Failed to load messages",

    // Cofounder Page
    "cofounder.title": "Find Co-founders",
    "cofounder.description": "Connect with entrepreneurs and build your startup together",
    "cofounder.startups": "Startups",
    "cofounder.cofounders": "Co-founders",
    "cofounder.noStartups": "No startups found. Be the first to create one!",

    // Competition Page
    "competition.title": "Find Competition Teams",
    "competition.description": "Join teams for hackathons, case competitions, and challenges",
    "competition.competitions": "Competitions",
    "competition.teammates": "Teammates",
    "competition.noCompetitions": "No competitions found. Create your team and start recruiting!",
    "competition.competitionType": "Competition Type",
    "competition.hackathon": "Hackathon",
    "competition.caseCompetition": "Case Competition",
    "competition.designChallenge": "Design Challenge",
    "competition.other": "Other",

    // Create Team
    "createTeam.button": "Create Team",
    "createTeam.titleStartup": "Create Startup Team",
    "createTeam.titleCompetition": "Create Competition Team",
    "createTeam.descStartup": "Start recruiting co-founders and team members for your startup",
    "createTeam.descCompetition": "Find teammates for your upcoming competition or hackathon",
    "createTeam.name": "Team Name",
    "createTeam.namePlaceholder": "e.g., AI Learning Platform",
    "createTeam.description": "Description",
    "createTeam.descriptionPlaceholder": "Tell people about your team and what you're building...",
    "createTeam.stage": "Stage",
    "createTeam.selectStage": "Select stage",
    "createTeam.stageIdea": "Idea",
    "createTeam.stageMVP": "MVP",
    "createTeam.stageGrowth": "Growth",
    "createTeam.stageScale": "Scale",
    "createTeam.industry": "Industry",
    "createTeam.location": "Location",
    "createTeam.locationPlaceholder": "e.g., Remote, San Francisco",
    "createTeam.teamSize": "Team Size",
    "createTeam.openRoles": "Open Roles",
    "createTeam.addRole": "e.g., Frontend Developer",
    "createTeam.lookingFor": "What We're Looking For",
    "createTeam.lookingForPlaceholder": "Describe the kind of people you want to join your team...",
    "createTeam.website": "Website",
    "createTeam.equityOffered": "Equity Offered",
    "createTeam.create": "Create Team",
    "createTeam.creating": "Creating...",
    "createTeam.success": "Team created successfully!",
    "createTeam.error": "Failed to create team. Please try again.",
    "createTeam.loginRequired": "You must be logged in to create a team.",
    "cancel": "Cancel",
    "success": "Success",
    "error": "Error",
    
    // Team Detail
    "loading": "Loading...",
    "back": "Back",
    "description": "Description",
    "lookingFor": "What We're Looking For",
    "openRoles": "Open Roles",
    "teamInfo": "Team Info",
    "members": "members",
    "founder": "Founder",
    "sendMessage": "Send Message",

    // Onboarding
    "onboarding.step": "Step",
    "onboarding.of": "of",
    "onboarding.optional": "Optional",
    "onboarding.back": "Back",
    "onboarding.next": "Next",
    "onboarding.skip": "Skip",
    "onboarding.finish": "Finish",
    "onboarding.saving": "Saving...",
    "onboarding.complete": "Profile Complete!",
    "onboarding.completeDesc": "Your profile has been set up successfully.",
    "onboarding.saveError": "Failed to save progress. Please try again.",
    
    // Step 1
    "onboarding.step1Title": "Basic Information",
    "onboarding.step1Desc": "Let's start with your basic information",
    "onboarding.profilePicture": "Profile Picture URL",
    "onboarding.profilePicturePlaceholder": "https://example.com/your-photo.jpg",
    "onboarding.fullName": "Full Name",
    "onboarding.fullNamePlaceholder": "Enter your full name",
    "onboarding.email": "Email",
    "onboarding.emailPlaceholder": "your@email.com",
    "onboarding.linkedIn": "LinkedIn URL",
    "onboarding.location": "Location",
    "onboarding.locationPlaceholder": "City, Country",
    
    // Step 2
    "onboarding.step2Title": "Professional Background",
    "onboarding.step2Desc": "Tell us about your professional background",
    "onboarding.bio": "Bio / Introduction",
    "onboarding.bioPlaceholder": "Tell us about yourself, your experience, and what you're passionate about...",
    "onboarding.accomplishment": "Impressive Accomplishment",
    "onboarding.accomplishmentPlaceholder": "Share your most impressive achievement...",
    "onboarding.accomplishmentHint": "What's something you've done that you're proud of?",
    "onboarding.technical": "Are you technical?",
    "onboarding.technicalDesc": "You are a programmer, scientist or engineer who can build the product without outside assistance.",
    "onboarding.yes": "Yes",
    "onboarding.no": "No",
    
    // Step 3
    "onboarding.step3Title": "Education & Employment",
    "onboarding.step3Desc": "Add your education and work experience (optional)",
    "onboarding.education": "Education",
    "onboarding.addEducation": "Add Education",
    "onboarding.noEducation": "No education added yet. Click 'Add Education' to add one.",
    "onboarding.school": "School / University",
    "onboarding.schoolPlaceholder": "e.g., Stanford University",
    "onboarding.degree": "Degree",
    "onboarding.degreePlaceholder": "e.g., Bachelor's, Master's",
    "onboarding.fieldOfStudy": "Field of Study",
    "onboarding.fieldPlaceholder": "e.g., Computer Science",
    "onboarding.graduationYear": "Graduation Year",
    "onboarding.employment": "Employment",
    "onboarding.addEmployment": "Add Employment",
    "onboarding.noEmployment": "No employment added yet. Click 'Add Employment' to add one.",
    "onboarding.employer": "Employer",
    "onboarding.employerPlaceholder": "e.g., Google",
    "onboarding.position": "Position / Title",
    "onboarding.positionPlaceholder": "e.g., Software Engineer",
    "onboarding.startDate": "Start Date",
    "onboarding.endDate": "End Date",
    "onboarding.currentJob": "I currently work here",
    
    // Step 4
    "onboarding.step4Title": "Personal Information",
    "onboarding.step4Desc": "A few more details about you (optional)",
    "onboarding.gender": "Gender",
    "onboarding.selectGender": "Select gender",
    "onboarding.male": "Male",
    "onboarding.female": "Female",
    "onboarding.nonBinary": "Non-binary",
    "onboarding.preferNotSay": "Prefer not to say",
    "onboarding.birthdate": "Date of Birth",
    "onboarding.socialMedia": "Social Media URL",
    "onboarding.socialMediaPlaceholder": "https://twitter.com/yourhandle",
    "onboarding.socialMediaHint": "Twitter, Instagram, or other social media profile",
    
    // Step 5
    "onboarding.step5Title": "Startup Readiness",
    "onboarding.step5Desc": "Tell us about your startup plans and interests",
    "onboarding.hasIdea": "Do you already have a startup or idea that you're set on?",
    "onboarding.ideaCommitted": "Yes, I'm committed to an idea and I want a co-founder who can help me build it",
    "onboarding.ideaExploring": "I have some ideas, but I'm also open to exploring other ideas",
    "onboarding.ideaOpen": "No, I could help a co-founder with their existing idea or explore new ideas together",
    "onboarding.whatIdeas": "What are some ideas you're interested in pursuing?",
    "onboarding.ideasPlaceholder": "Describe your startup idea(s)...",
    "onboarding.hasCofounder": "Do you already have a co-founder?",
    "onboarding.fulltimeWhen": "When do you want to start working on a startup full-time?",
    "onboarding.ftAlready": "I'm already full-time on my startup",
    "onboarding.ftReady": "I'm ready to go full-time as soon as I meet the right co-founder",
    "onboarding.ftYear": "I'm planning to go full-time in the next year",
    "onboarding.ftNoPlans": "I don't have any specific plans yet",
    "onboarding.responsibilityAreas": "Which areas of a startup are you willing to take responsibility for?",
    "onboarding.interests": "Which topics and industries are you interested in?",
    "onboarding.interestsHint": "We'll try to show you more profiles from founders with common interests.",
    
    // Responsibility areas
    "onboarding.area.product": "Product",
    "onboarding.area.engineering": "Engineering",
    "onboarding.area.design": "Design",
    "onboarding.area.marketing": "Marketing",
    "onboarding.area.sales": "Sales",
    "onboarding.area.operations": "Operations",
    "onboarding.area.finance": "Finance",
    "onboarding.area.legal": "Legal",
    "onboarding.area.hr": "HR / People",
    "onboarding.area.customer_success": "Customer Success",
    
    // Interests
    "onboarding.interest.ai": "Artificial Intelligence",
    "onboarding.interest.b2b": "B2B / Enterprise",
    "onboarding.interest.developer_tools": "Developer Tools",
    "onboarding.interest.education": "Education / Edtech",
    "onboarding.interest.energy": "Energy",
    "onboarding.interest.entertainment": "Entertainment",
    "onboarding.interest.fintech": "Fintech",
    "onboarding.interest.health": "Health / Healthcare",
    "onboarding.interest.hardware": "Hardware",
    "onboarding.interest.robotics": "Robotics",
    "onboarding.interest.travel": "Travel / Tourism",
    "onboarding.interest.ecommerce": "E-commerce",
    "onboarding.interest.social": "Social",
    "onboarding.interest.climate": "Climate / Sustainability",
    
    // Step 6
    "onboarding.step6Title": "Personal & Values",
    "onboarding.step6Desc": "Help potential co-founders get to know you better (optional)",
    "onboarding.equityExpectation": "What are your expectations for splitting equity?",
    "onboarding.equityHint": "YC strongly recommends an equal split.",
    "onboarding.equityEqual": "Equal split (50/50)",
    "onboarding.equityFlexible": "Flexible based on contribution",
    "onboarding.equityNegotiable": "Open to negotiation",
    "onboarding.hobbies": "What do you do with your free time?",
    "onboarding.hobbiesPlaceholder": "Share your hobbies and interests...",
    "onboarding.lifePath": "How did your life path lead to where you are now?",
    "onboarding.lifePathHint": "How have your experiences shaped your values?",
    "onboarding.lifePathPlaceholder": "Share your story...",
    "onboarding.additionalInfo": "Anything else you would like to add about yourself?",
    "onboarding.additionalInfoHint": "Feel free to write anything else that you'd like a co-founder to know about you.",
    "onboarding.additionalInfoPlaceholder": "Anything else...",
    
    // Step 7
    "onboarding.step7Title": "Co-founder Preferences",
    "onboarding.step7Desc": "What are you looking for in a co-founder?",
    "onboarding.cfIdeaPref": "Are you looking for a co-founder who already has a specific idea?",
    "onboarding.cfWantsIdea": "I want to see co-founders who have a specific idea",
    "onboarding.cfNoIdea": "I want to see co-founders who are not set on a specific idea",
    "onboarding.noPreference": "No preference",
    "onboarding.cfTechPref": "Do you prefer either technical or non-technical profiles?",
    "onboarding.nonTechnical": "Non-technical",
    "onboarding.cfTimingPref": "Do you prefer to see co-founders who match up with your timing?",
    "onboarding.cfTimingOnly": "I only want to see co-founders who match my timing",
    "onboarding.cfTimingPrefer": "I prefer to see co-founders who match my timing, but it's not required",
    "onboarding.cfLocationPref": "Do you have a location preference?",
    "onboarding.cfLocNearby": "Within a certain distance of me",
    "onboarding.cfLocCountry": "In my country",
    "onboarding.cfLocRegion": "In my region",
    "onboarding.cfDistance": "Distance",
    "onboarding.cfAgePref": "Do you have an age preference?",
    "onboarding.cfAgeRange": "Within a certain age range",
    "onboarding.minAge": "Min Age",
    "onboarding.maxAge": "Max Age",
    "onboarding.cfResponsibility": "Which areas would you like a co-founder to take responsibility for?",
    "onboarding.cfInterestPref": "Do you prefer to match candidates who share your interests?",
    "onboarding.cfInterestOnly": "I only want to match with co-founders who share my interests",
    "onboarding.cfInterestPrefer": "I prefer to match with co-founders who share my interests, but it's not required",
  },
  zh: {
    // Navigation
    "nav.browse": "浏览",
    "nav.messages": "消息",
    "nav.account": "账户",
    "nav.myProfile": "我的资料",
    "nav.logOut": "退出登录",
    "nav.signIn": "登录",
    "nav.getStarted": "开始使用",
    
    // Hero
    "hero.badge": "找到完美的合伙人",
    "hero.title1": "找到你的完美",
    "hero.title2": "队友",
    "hero.description": "无论你是创建初创公司还是参加黑客马拉松，都能找到合适的人来实现你的想法。",
    "hero.getStarted": "开始使用",
    "hero.browseNow": "立即浏览",
    "hero.freeJoin": "✨ 免费加入 • 🔒 无需信用卡",
    "hero.activeMembers": "活跃会员",
    "hero.teamsFormed": "组建团队",
    "hero.universities": "大学",
    "hero.testimonial": "2天内找到了她的CTO",
    
    // PathSelector
    "path.title": "选择你的路径",
    "path.description": "无论你是参加比赛还是构建下一个大项目，都能找到完美的队友",
    "path.competitions": "比赛与黑客马拉松",
    "path.competitionsDesc": "为黑客马拉松、案例竞赛、创新挑战赛和学术竞赛寻找队友",
    "path.competitionsFeature1": "非常适合学生和竞赛爱好者",
    "path.competitionsFeature2": "有明确截止日期的短期项目",
    "path.competitionsFeature3": "按技能、时区和可用性匹配",
    "path.findCompetitionTeams": "寻找竞赛团队",
    "path.startups": "初创公司与创业",
    "path.startupsDesc": "与联合创始人和早期团队成员联系，从想法到启动建立你的初创公司",
    "path.startupsFeature1": "适合有抱负的创始人和企业家",
    "path.startupsFeature2": "长期承诺和股权合作",
    "path.startupsFeature3": "找到与你愿景一致的联合创始人",
    "path.findCoFounders": "寻找联合创始人",
    
    // Features
    "features.title1": "你需要的一切",
    "features.title2": "找到你的团队",
    "features.description": "CoLabNow让有抱负的企业家和学生的团队建设变得简单、快速和有效。",
    "features.smartMatching": "智能匹配",
    "features.smartMatchingDesc": "根据技能、兴趣、时区和目标寻找联合创始人。我们的筛选器帮助你发现完美匹配。",
    "features.teamBuilding": "团队建设",
    "features.teamBuildingDesc": "浏览正在寻找成员的团队或创建你自己的团队列表。非常适合黑客马拉松和初创公司竞赛。",
    "features.advancedFilters": "高级筛选",
    "features.advancedFiltersDesc": "按角色、行业、学校、语言、位置等筛选。准确找到你要找的人。",
    "features.directConnect": "直接联系",
    "features.directConnectDesc": "直接给潜在的联合创始人发消息。在承诺合作之前建立关系。",
    "features.globalCommunity": "全球社区",
    "features.globalCommunityDesc": "与来自世界各地大学和社区的企业家和创新者联系。",
    "features.fastSimple": "快速简单",
    "features.fastSimpleDesc": "几分钟内创建你的个人资料并开始连接。没有复杂的入职或冗长的表格。",
    
    // HowItWorks
    "how.title": "工作原理",
    "how.description": "几分钟内开始并找到你的完美联合创始人或团队",
    "how.step1": "创建你的资料",
    "how.step1Desc": "注册并告诉我们你的技能、兴趣以及你在联合创始人或团队中寻找什么。",
    "how.step2": "浏览和筛选",
    "how.step2Desc": "搜索企业家和团队的资料。使用筛选器找到满足你需求的完美匹配。",
    "how.step3": "连接和聊天",
    "how.step3Desc": "联系潜在的联合创始人或团队。进行对话以了解你们是否一致。",
    "how.step4": "共同建设",
    "how.step4Desc": "开始你的旅程！在你的初创公司上工作，参加黑客马拉松，或将你的想法变为现实。",
    
    // CTA
    "cta.title": "准备好找到你的联合创始人了吗？",
    "cta.description": "加入数千名正在共同构建未来的企业家、开发者和创新者。",
    "cta.getStartedFree": "免费开始",
    "cta.browseProfiles": "浏览资料",
    
    // Footer
    "footer.tagline": "连接企业家和创新者，共同构建未来。",
    "footer.platform": "平台",
    "footer.browse": "浏览",
    "footer.howItWorks": "工作原理",
    "footer.successStories": "成功案例",
    "footer.resources": "资源",
    "footer.blog": "博客",
    "footer.faq": "常见问题",
    "footer.support": "支持",
    "footer.company": "公司",
    "footer.about": "关于",
    "footer.privacy": "隐私",
    "footer.terms": "条款",
    "footer.copyright": "© 2025 CoLabNow. 保留所有权利。",
    
    // Auth
    "auth.welcome": "欢迎来到CoLabNow",
    "auth.signIn": "登录",
    "auth.signUp": "注册",
    "auth.email": "邮箱",
    "auth.password": "密码",
    "auth.signInButton": "登录",
    "auth.signUpButton": "注册",
    "auth.noAccount": "还没有账户？",
    "auth.haveAccount": "已有账户？",
    "auth.signUpLink": "注册",
    "auth.signInLink": "登录",
    
    // Profile
    "profile.myProfile": "我的资料",
    "profile.fullName": "全名",
    "profile.school": "学校/大学",
    "profile.role": "角色",
    "profile.bio": "个人简介",
    "profile.location": "位置",
    "profile.timezone": "时区",
    "profile.languages": "语言",
    "profile.skills": "技能",
    "profile.linkedin": "LinkedIn链接",
    "profile.github": "GitHub链接",
    "profile.portfolio": "作品集链接",
    "profile.availability": "可用性",
    "profile.available": "可用",
    "profile.busy": "繁忙",
    "profile.notLooking": "不寻找",
    "profile.saveChanges": "保存更改",
    "profile.experienceLevel": "经验水平",
    "profile.beginner": "初学者",
    "profile.intermediate": "中级",
    "profile.advanced": "高级",
    "profile.expert": "专家",
    
    // Browse
    "browse.title": "浏览",
    "browse.profiles": "资料",
    "browse.teams": "团队",
    "browse.searchPlaceholder": "按名称、技能或角色搜索...",
    "browse.filterByRole": "按角色筛选",
    "browse.all": "全部",
    "browse.connect": "连接",
    "browse.viewTeam": "查看团队",
    "browse.openRoles": "开放职位",
    "browse.teamSize": "团队规模",
    "browse.members": "成员",
    "browse.loading": "加载中...",
    "browse.loadingDesc": "寻找完美匹配",
    "browse.discover": "发现你的",
    "browse.perfectMatch": "完美匹配",
    "browse.browseDesc": "浏览有抱负的企业家和寻找成员的团队资料",
    "browse.filters": "筛选",
    "browse.role": "角色",
    "browse.developer": "开发者",
    "browse.designer": "设计师",
    "browse.business": "商业",
    "browse.marketing": "市场营销",
    "browse.industry": "行业",
    "browse.availability": "可用性",
    "browse.fulltime": "全职",
    "browse.parttime": "兼职",
    "browse.flexible": "灵活",
    "browse.noProfiles": "未找到资料。成为第一个创建的！",
    "browse.noTeams": "未找到团队。创建你的团队并开始招募！",
    
    // Auth
    "auth.fullName": "全名",
    "auth.signUpDesc": "加入CoLabNow并开始建立你的梦想团队",
    "auth.signInDesc": "登录以继续你的旅程",
    "auth.passwordHint": "至少6个字符",
    "auth.loading": "加载中...",
    "auth.terms": "继续即表示您同意我们的服务条款和隐私政策",
    
    // Profile
    "profile.loading": "加载中...",
    "profile.interestedIn": "我感兴趣",
    "profile.competitions": "比赛与黑客马拉松",
    "profile.startups": "初创公司与创业",
    "profile.both": "两者都有",
    "profile.bioPlaceholder": "告诉我们关于你自己...",
    "profile.addSkill": "添加技能...",
    "profile.add": "添加",
    "profile.saving": "保存中...",
    "profile.update": "更新资料",
    "profile.updating": "更新中...",
    "profile.success": "成功",
    "profile.profileUpdated": "资料更新成功！",
    
    // Messages
    "message.sendTo": "发送消息给",
    "message.dialogDesc": "发送直接消息以联系并讨论合作机会。",
    "message.subject": "主题",
    "message.subjectPlaceholder": "你想讨论什么？",
    "message.message": "消息",
    "message.messagePlaceholder": "在这里写下你的消息...",
    "message.cancel": "取消",
    "message.send": "发送消息",
    "message.sending": "发送中...",
    "message.sent": "消息已发送",
    "message.sentDesc": "你的消息已成功发送！",
    "message.sendError": "发送消息失败",
    "message.emptyMessage": "消息为空",
    "message.emptyMessageDesc": "发送前请写下消息内容。",
    "message.loginRequired": "需要登录",
    "message.loginRequiredDesc": "你需要登录才能发送消息。",
    "message.noSubject": "无主题",

    // Messages Page
    "messages.inbox": "收件箱",
    "messages.inboxDesc": "查看和管理你的消息",
    "messages.loading": "加载消息中...",
    "messages.noMessages": "还没有消息",
    "messages.new": "新",
    "messages.back": "返回",
    "messages.reply": "回复",
    "messages.replyPlaceholder": "在这里输入你的回复...",
    "messages.sendReply": "发送回复",
    "messages.replySent": "回复已发送",
    "messages.replySentDesc": "你的回复已成功发送！",
    "messages.selectMessage": "选择一条消息查看",
    "messages.loadError": "加载消息失败",

    // Cofounder Page
    "cofounder.title": "寻找联合创始人",
    "cofounder.description": "与企业家联系，共同建立你的初创公司",
    "cofounder.startups": "初创公司",
    "cofounder.cofounders": "联合创始人",
    "cofounder.noStartups": "未找到初创公司。成为第一个创建的！",

    // Competition Page
    "competition.title": "寻找竞赛团队",
    "competition.description": "加入黑客马拉松、案例竞赛和挑战的团队",
    "competition.competitions": "竞赛",
    "competition.teammates": "队友",
    "competition.noCompetitions": "未找到竞赛。创建你的团队并开始招募！",
    "competition.competitionType": "竞赛类型",
    "competition.hackathon": "黑客马拉松",
    "competition.caseCompetition": "案例竞赛",
    "competition.designChallenge": "设计挑战",
    "competition.other": "其他",

    // Create Team
    "createTeam.button": "创建团队",
    "createTeam.titleStartup": "创建初创团队",
    "createTeam.titleCompetition": "创建竞赛团队",
    "createTeam.descStartup": "开始为你的初创公司招募联合创始人和团队成员",
    "createTeam.descCompetition": "为你即将参加的竞赛或黑客马拉松寻找队友",
    "createTeam.name": "团队名称",
    "createTeam.namePlaceholder": "例如：AI学习平台",
    "createTeam.description": "描述",
    "createTeam.descriptionPlaceholder": "告诉大家你的团队和你正在构建的项目...",
    "createTeam.stage": "阶段",
    "createTeam.selectStage": "选择阶段",
    "createTeam.stageIdea": "想法",
    "createTeam.stageMVP": "最小可行产品",
    "createTeam.stageGrowth": "增长",
    "createTeam.stageScale": "规模化",
    "createTeam.industry": "行业",
    "createTeam.location": "位置",
    "createTeam.locationPlaceholder": "例如：远程、旧金山",
    "createTeam.teamSize": "团队规模",
    "createTeam.openRoles": "空缺职位",
    "createTeam.addRole": "例如：前端开发",
    "createTeam.lookingFor": "我们正在寻找",
    "createTeam.lookingForPlaceholder": "描述你希望加入团队的人...",
    "createTeam.website": "网站",
    "createTeam.equityOffered": "提供股权",
    "createTeam.create": "创建团队",
    "createTeam.creating": "创建中...",
    "createTeam.success": "团队创建成功！",
    "createTeam.error": "创建团队失败。请重试。",
    "createTeam.loginRequired": "你必须登录才能创建团队。",
    "cancel": "取消",
    "success": "成功",
    "error": "错误",
    
    // Team Detail
    "loading": "加载中...",
    "back": "返回",
    "description": "描述",
    "lookingFor": "我们正在寻找",
    "openRoles": "空缺职位",
    "teamInfo": "团队信息",
    "members": "成员",
    "founder": "创始人",
    "sendMessage": "发送消息",

    // Onboarding
    "onboarding.step": "步骤",
    "onboarding.of": "/",
    "onboarding.optional": "可选",
    "onboarding.back": "返回",
    "onboarding.next": "下一步",
    "onboarding.skip": "跳过",
    "onboarding.finish": "完成",
    "onboarding.saving": "保存中...",
    "onboarding.complete": "资料完成！",
    "onboarding.completeDesc": "您的资料已成功设置。",
    "onboarding.saveError": "保存失败，请重试。",
    
    // Step 1
    "onboarding.step1Title": "基本信息",
    "onboarding.step1Desc": "让我们从您的基本信息开始",
    "onboarding.profilePicture": "头像链接",
    "onboarding.profilePicturePlaceholder": "https://example.com/your-photo.jpg",
    "onboarding.fullName": "全名",
    "onboarding.fullNamePlaceholder": "输入您的全名",
    "onboarding.email": "邮箱",
    "onboarding.emailPlaceholder": "your@email.com",
    "onboarding.linkedIn": "领英链接",
    "onboarding.location": "位置",
    "onboarding.locationPlaceholder": "城市，国家",
    
    // Step 2
    "onboarding.step2Title": "专业背景",
    "onboarding.step2Desc": "告诉我们您的专业背景",
    "onboarding.bio": "个人简介",
    "onboarding.bioPlaceholder": "介绍一下您自己、您的经验和您热衷的事情...",
    "onboarding.accomplishment": "突出成就",
    "onboarding.accomplishmentPlaceholder": "分享您最令人印象深刻的成就...",
    "onboarding.accomplishmentHint": "您做过什么让您感到自豪的事情？",
    "onboarding.technical": "您是技术人员吗？",
    "onboarding.technicalDesc": "您是程序员、科学家或工程师，可以独立构建产品。",
    "onboarding.yes": "是",
    "onboarding.no": "否",
    
    // Step 3
    "onboarding.step3Title": "教育与工作经历",
    "onboarding.step3Desc": "添加您的教育和工作经历（可选）",
    "onboarding.education": "教育经历",
    "onboarding.addEducation": "添加教育经历",
    "onboarding.noEducation": "尚未添加教育经历。点击'添加教育经历'来添加。",
    "onboarding.school": "学校/大学",
    "onboarding.schoolPlaceholder": "例如：斯坦福大学",
    "onboarding.degree": "学位",
    "onboarding.degreePlaceholder": "例如：学士、硕士",
    "onboarding.fieldOfStudy": "专业领域",
    "onboarding.fieldPlaceholder": "例如：计算机科学",
    "onboarding.graduationYear": "毕业年份",
    "onboarding.employment": "工作经历",
    "onboarding.addEmployment": "添加工作经历",
    "onboarding.noEmployment": "尚未添加工作经历。点击'添加工作经历'来添加。",
    "onboarding.employer": "雇主",
    "onboarding.employerPlaceholder": "例如：谷歌",
    "onboarding.position": "职位/头衔",
    "onboarding.positionPlaceholder": "例如：软件工程师",
    "onboarding.startDate": "开始日期",
    "onboarding.endDate": "结束日期",
    "onboarding.currentJob": "我目前在这里工作",
    
    // Step 4
    "onboarding.step4Title": "个人信息",
    "onboarding.step4Desc": "关于您的更多详情（可选）",
    "onboarding.gender": "性别",
    "onboarding.selectGender": "选择性别",
    "onboarding.male": "男",
    "onboarding.female": "女",
    "onboarding.nonBinary": "非二元性别",
    "onboarding.preferNotSay": "不想透露",
    "onboarding.birthdate": "出生日期",
    "onboarding.socialMedia": "社交媒体链接",
    "onboarding.socialMediaPlaceholder": "https://twitter.com/yourhandle",
    "onboarding.socialMediaHint": "Twitter、Instagram或其他社交媒体资料",
    
    // Step 5
    "onboarding.step5Title": "创业准备",
    "onboarding.step5Desc": "告诉我们您的创业计划和兴趣",
    "onboarding.hasIdea": "您是否已经有一个确定的创业想法？",
    "onboarding.ideaCommitted": "是的，我已经确定了一个想法，我想找一个能帮我实现它的联合创始人",
    "onboarding.ideaExploring": "我有一些想法，但也愿意探索其他想法",
    "onboarding.ideaOpen": "没有，我可以帮助联合创始人实现他们的想法，或一起探索新想法",
    "onboarding.whatIdeas": "您有兴趣追求哪些想法？",
    "onboarding.ideasPlaceholder": "描述您的创业想法...",
    "onboarding.hasCofounder": "您是否已经有联合创始人？",
    "onboarding.fulltimeWhen": "您计划什么时候全职投入创业？",
    "onboarding.ftAlready": "我已经全职投入创业",
    "onboarding.ftReady": "一旦遇到合适的联合创始人，我就准备好全职投入",
    "onboarding.ftYear": "我计划在明年内全职投入",
    "onboarding.ftNoPlans": "我还没有具体计划",
    "onboarding.responsibilityAreas": "您愿意负责创业公司的哪些领域？",
    "onboarding.interests": "您对哪些主题和行业感兴趣？",
    "onboarding.interestsHint": "我们会尝试向您展示更多有共同兴趣的创始人资料。",
    
    // Responsibility areas
    "onboarding.area.product": "产品",
    "onboarding.area.engineering": "工程",
    "onboarding.area.design": "设计",
    "onboarding.area.marketing": "市场营销",
    "onboarding.area.sales": "销售",
    "onboarding.area.operations": "运营",
    "onboarding.area.finance": "财务",
    "onboarding.area.legal": "法务",
    "onboarding.area.hr": "人力资源",
    "onboarding.area.customer_success": "客户成功",
    
    // Interests
    "onboarding.interest.ai": "人工智能",
    "onboarding.interest.b2b": "B2B/企业服务",
    "onboarding.interest.developer_tools": "开发者工具",
    "onboarding.interest.education": "教育/教育科技",
    "onboarding.interest.energy": "能源",
    "onboarding.interest.entertainment": "娱乐",
    "onboarding.interest.fintech": "金融科技",
    "onboarding.interest.health": "健康/医疗",
    "onboarding.interest.hardware": "硬件",
    "onboarding.interest.robotics": "机器人",
    "onboarding.interest.travel": "旅游/旅行",
    "onboarding.interest.ecommerce": "电子商务",
    "onboarding.interest.social": "社交",
    "onboarding.interest.climate": "气候/可持续发展",
    
    // Step 6
    "onboarding.step6Title": "个人与价值观",
    "onboarding.step6Desc": "帮助潜在的联合创始人更好地了解您（可选）",
    "onboarding.equityExpectation": "您对股权分配有什么期望？",
    "onboarding.equityHint": "YC强烈建议平等分配。",
    "onboarding.equityEqual": "平等分配（50/50）",
    "onboarding.equityFlexible": "根据贡献灵活分配",
    "onboarding.equityNegotiable": "可以协商",
    "onboarding.hobbies": "您的业余时间做什么？",
    "onboarding.hobbiesPlaceholder": "分享您的爱好和兴趣...",
    "onboarding.lifePath": "您的人生经历如何引导您走到今天？",
    "onboarding.lifePathHint": "您的经历如何塑造了您的价值观？",
    "onboarding.lifePathPlaceholder": "分享您的故事...",
    "onboarding.additionalInfo": "还有什么想补充的吗？",
    "onboarding.additionalInfoHint": "随时写下您希望联合创始人了解的任何其他内容。",
    "onboarding.additionalInfoPlaceholder": "其他信息...",
    
    // Step 7
    "onboarding.step7Title": "联合创始人偏好",
    "onboarding.step7Desc": "您在联合创始人身上寻找什么？",
    "onboarding.cfIdeaPref": "您是否在寻找已经有具体想法的联合创始人？",
    "onboarding.cfWantsIdea": "我想看有具体想法的联合创始人",
    "onboarding.cfNoIdea": "我想看没有确定想法的联合创始人",
    "onboarding.noPreference": "没有偏好",
    "onboarding.cfTechPref": "您更喜欢技术型还是非技术型的资料？",
    "onboarding.nonTechnical": "非技术型",
    "onboarding.cfTimingPref": "您是否希望看到时间安排与您匹配的联合创始人？",
    "onboarding.cfTimingOnly": "我只想看时间安排与我匹配的联合创始人",
    "onboarding.cfTimingPrefer": "我更希望看到时间匹配的联合创始人，但不是必须的",
    "onboarding.cfLocationPref": "您有位置偏好吗？",
    "onboarding.cfLocNearby": "在我附近一定距离内",
    "onboarding.cfLocCountry": "在我的国家内",
    "onboarding.cfLocRegion": "在我的地区内",
    "onboarding.cfDistance": "距离",
    "onboarding.cfAgePref": "您有年龄偏好吗？",
    "onboarding.cfAgeRange": "在一定年龄范围内",
    "onboarding.minAge": "最小年龄",
    "onboarding.maxAge": "最大年龄",
    "onboarding.cfResponsibility": "您希望联合创始人负责哪些领域？",
    "onboarding.cfInterestPref": "您是否希望匹配与您有共同兴趣的候选人？",
    "onboarding.cfInterestOnly": "我只想匹配与我有共同兴趣的联合创始人",
    "onboarding.cfInterestPrefer": "我更希望匹配有共同兴趣的联合创始人，但不是必须的",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
